name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements-dev.txt
      - name: Flake8
        run: |
          flake8 demo
      - name: Isort
        run: |
          isort demo --check
      - name: Black demo
        run: |
          black demo --check
      - name: Run Tests
        run: |
          python demo/manage.py test
