name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install -r requirements.test.dev
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run flake8
        run: |
          python flake8 .
      - name: Run isort
        run: |
          python isort --check .
      - name: Run black
        run: |
          python black --check .
      - name: Run Tests
        run: |
          python manage.py test
